
import React, { useRef } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Share2, Download } from 'lucide-react';

interface ShareableScoreCardProps {
  score: number;
  betterThan?: number;
}

const ShareableScoreCard: React.FC<ShareableScoreCardProps> = ({ score, betterThan }) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const generateShareableImage = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    // Set canvas size for Instagram (1080x1080)
    canvas.width = 1080;
    canvas.height = 1080;

    // Background gradient
    const gradient = ctx.createLinearGradient(0, 0, 1080, 1080);
    gradient.addColorStop(0, '#4B5563');
    gradient.addColorStop(1, '#64748B');
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, 1080, 1080);

    // Add sketchy border
    ctx.strokeStyle = '#E5E7EB';
    ctx.lineWidth = 8;
    ctx.setLineDash([20, 10]);
    ctx.strokeRect(40, 40, 1000, 1000);
    ctx.setLineDash([]);

    // Title
    ctx.fillStyle = '#FFFFFF';
    ctx.font = 'bold 80px Arial';
    ctx.textAlign = 'left';
    ctx.fillText('Design Score', 80, 180);

    // Score
    ctx.font = 'bold 200px Arial';
    ctx.fillText(`${score}/100`, 80, 420);

    // Draw sketchy donut chart
    const centerX = 700;
    const centerY = 350;
    const radius = 150;
    const innerRadius = 100;

    // Background circle (sketchy)
    ctx.strokeStyle = '#374151';
    ctx.lineWidth = 50;
    ctx.beginPath();
    ctx.arc(centerX, centerY, radius - 25, 0, 2 * Math.PI);
    ctx.stroke();

    // Score arc (sketchy green)
    ctx.strokeStyle = '#10B981';
    ctx.lineWidth = 50;
    ctx.beginPath();
    const endAngle = (score / 100) * 2 * Math.PI - Math.PI / 2;
    ctx.arc(centerX, centerY, radius - 25, -Math.PI / 2, endAngle);
    ctx.stroke();

    // Center text
    ctx.fillStyle = '#FFFFFF';
    ctx.font = 'bold 60px Arial';
    ctx.textAlign = 'center';
    ctx.fillText(`${score}%`, centerX, centerY - 10);
    ctx.font = '30px Arial';
    ctx.fillText('Overall Score', centerX, centerY + 30);

    // Add sketchy decorative elements
    drawSketchyArrow(ctx, 200, 500, 45);
    drawSketchyChart(ctx, 120, 600);
    drawSketchyStars(ctx, 600, 550);

    // Better than text
    if (betterThan) {
      ctx.fillStyle = '#FFFFFF';
      ctx.font = 'bold 40px Arial';
      ctx.textAlign = 'left';
      ctx.fillText(`Better than ${betterThan}%`, 80, 800);
      ctx.font = '32px Arial';
      ctx.fillText('of analyzed websites', 80, 850);
    }

    // Add watermark
    ctx.fillStyle = '#9CA3AF';
    ctx.font = '24px Arial';
    ctx.textAlign = 'right';
    ctx.fillText('Generated by UX Ray', 1000, 1020);
  };

  const drawSketchyArrow = (ctx: CanvasRenderingContext2D, x: number, y: number, size: number) => {
    ctx.strokeStyle = '#FFFFFF';
    ctx.lineWidth = 3;
    ctx.beginPath();
    ctx.moveTo(x, y);
    ctx.lineTo(x + size, y - size / 2);
    ctx.lineTo(x + size * 0.7, y - size / 2);
    ctx.lineTo(x + size, y - size / 2);
    ctx.lineTo(x + size * 0.7, y - size / 4);
    ctx.stroke();
  };

  const drawSketchyChart = (ctx: CanvasRenderingContext2D, x: number, y: number) => {
    ctx.strokeStyle = '#FFFFFF';
    ctx.lineWidth = 2;
    const bars = [30, 50, 40, 60, 45];
    bars.forEach((height, i) => {
      ctx.strokeRect(x + i * 25, y - height, 20, height);
    });
  };

  const drawSketchyStars = (ctx: CanvasRenderingContext2D, x: number, y: number) => {
    ctx.fillStyle = '#FEF08A';
    ctx.font = '30px Arial';
    for (let i = 0; i < 5; i++) {
      ctx.fillText('★', x + i * 35, y);
    }
  };

  const downloadImage = () => {
    generateShareableImage();
    const canvas = canvasRef.current;
    if (!canvas) return;

    const link = document.createElement('a');
    link.download = `design-score-${score}.png`;
    link.href = canvas.toDataURL();
    link.click();
  };

  const shareToInstagram = () => {
    generateShareableImage();
    const canvas = canvasRef.current;
    if (!canvas) return;

    canvas.toBlob((blob) => {
      if (blob && navigator.share) {
        const file = new File([blob], `design-score-${score}.png`, { type: 'image/png' });
        navigator.share({
          files: [file],
          title: 'My Design Score',
          text: `My website scored ${score}/100 in UX analysis!`
        }).catch(console.error);
      } else {
        // Fallback: download the image
        downloadImage();
      }
    }, 'image/png');
  };

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button 
          variant="outline" 
          className="bg-white/20 border-white/30 text-white hover:bg-white/30 border-2 border-dashed"
        >
          <Share2 className="h-4 w-4 mr-2" />
          Share
        </Button>
      </DialogTrigger>
      
      <DialogContent className="max-w-md bg-white">
        <DialogHeader>
          <DialogTitle className="text-center text-gray-800">Share Your Design Score</DialogTitle>
        </DialogHeader>
        
        <div className="space-y-4">
          {/* Preview */}
          <div className="relative">
            <canvas
              ref={canvasRef}
              className="w-full h-auto max-w-sm mx-auto border-2 border-dashed border-gray-300 rounded"
              style={{ aspectRatio: '1/1' }}
            />
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="text-center p-6 bg-gradient-to-br from-gray-600 to-slate-700 text-white rounded-lg border-2 border-dashed border-gray-300 w-full h-full flex flex-col justify-center"
                   style={{ fontFamily: '"Comic Sans MS", cursive' }}>
                
                <h3 className="text-2xl font-bold mb-2">Design Score</h3>
                <div className="text-5xl font-bold mb-4">{score}/100</div>
                
                {/* Mini donut chart representation */}
                <div className="flex justify-center mb-4">
                  <div className="relative w-20 h-20">
                    <svg className="w-20 h-20 transform -rotate-90">
                      <circle
                        cx="40"
                        cy="40"
                        r="30"
                        stroke="#374151"
                        strokeWidth="8"
                        fill="transparent"
                        strokeDasharray="8,4"
                      />
                      <circle
                        cx="40"
                        cy="40"
                        r="30"
                        stroke="#10B981"
                        strokeWidth="8"
                        fill="transparent"
                        strokeDasharray={`${(score / 100) * 188.5} 188.5`}
                        strokeLinecap="round"
                      />
                    </svg>
                    <div className="absolute inset-0 flex items-center justify-center">
                      <span className="text-sm font-bold">{score}%</span>
                    </div>
                  </div>
                </div>

                {betterThan && (
                  <p className="text-sm">
                    Better than <strong>{betterThan}%</strong><br />
                    of websites
                  </p>
                )}
                
                {/* Decorative sketchy elements */}
                <div className="flex justify-center mt-4 space-x-4 text-yellow-300">
                  <span>★</span>
                  <span>→</span>
                  <span>📊</span>
                  <span>↗</span>
                  <span>★</span>
                </div>
              </div>
            </div>
          </div>

          {/* Action buttons */}
          <div className="flex space-x-2">
            <Button 
              onClick={shareToInstagram}
              className="flex-1 bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white"
            >
              <Share2 className="h-4 w-4 mr-2" />
              Share to Instagram
            </Button>
            <Button 
              onClick={downloadImage}
              variant="outline"
              className="border-2 border-dashed border-gray-300"
            >
              <Download className="h-4 w-4" />
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default ShareableScoreCard;
