// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjnjtswrewnjkngqrbpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqbmp0c3dyZXduamtuZ3FyYnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzQ0MzQsImV4cCI6MjA2NDU1MDQzNH0.t_ZUtN6rFcCr0Owd3HyIRjdqaV0F3t6Ull4DMW8gi44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);